### ISSUE TITLE
findCoords() cannot determine location from clockloc--Tale 8. 

### ISSUE THREAD

**Issue by kaisejoe** [DashingStrike/Automato-ATITD#109]
In gatherer.lua, findCoords() is not returning a valid value and appears to be unable to determine the coords from the new clockloc in Tale 8. The clockloc is enabled and fully visible. 

As a side note, I'm unable to get anything to actually print to the console--is there something I'm missing, or is this a known issue?

**Comment by levi-rs** [comment]
I had this problem too, and it was due to the new clockloc UI. In the UI settings, there is an option to use the legacy UI, and selecting that fixed this particular issue for me.

**Comment by Jimbly** [comment]
Ah, console output is probably broken due to a change when I was forced to upgrade to Visual Studio 2017...  I should be able to put in a workaround for that and will release a new Automato patch soon.

As for the gather.lua issue, PRs that fix it, or make it work in both cases, are welcome!

**Comment by Jimbly** [comment]
Automato v2.18 has been released, fixing the console output issues.

**Comment by kaisejoe** [comment]
Great, thank you both! I'll try out v2.18 with the legacy UI this evening.

**Comment by wpattison** [comment]
Sorry, but I've updated and switched to Legacy UI and it is still crashing on unable to find clock. I'm in windowed mode. Any other tips/updates?

**Comment by Cegaiel** [comment]
Try moving the clock slightly. The new clock this tale is fancy background and fancy fonts.
If you Self Click -> Options -> Interface-Options , check the 'Use Legacy Interface' ; there shouldn't be any issues.

A good test for clock and windows in general are the scripts:
* test_ocr_clock.lua
* test_ocr_text.lua
* test_ocr_window (that Rotate button shows all open windows, one at a time)

But they all make a reference to the clock and is good to do testing.  While the scripts are running, you could try moving the clock around and see if the macro picks it up.

**Comment by ldobson** [comment]
Another thing I've seen in the past as an issue in the past windows scaling other than 100% - that breaks pretty much everything if it's set. You also need to make sure that font size small is set in game.

**Comment by Cegaiel** [comment]
![interface](https://user-images.githubusercontent.com/1331203/37557895-5cd3746c-2a03-11e8-9aac-b7df9bb1febd.png)

**Comment by wpattison** [comment]
Thank you all for the replies. I finally got it to work, I think the key was setting the interface size to small. To recap:

1. Run the game in windowed mode.
2. Set my desktop resolution to 1920x1080, maximize the game window.
3. Set Interface Size to Small.
4. Run the **test_ocr_clock.lua** script until it recognizes the clock.
