### ISSUE TITLE
cc_auto script

### ISSUE THREAD

**Issue by wzydhek** [DashingStrike/Automato-ATITD#110]
Anyone get the cc_auto script to work? I've had nothing but troubles with it this tale.

**Comment by Manon120184** [comment]
I have fixed this. When I get home from work I will submit the fixes for cc_auto and cc_assist.

**Comment by Catote** [comment]
Tried CC/auto out just now. I simply does nothing :=)

**Comment by Manon120184** [comment]
That is because I have not submitted the fix yet. Be patient hehe.

**Comment by ldobson** [comment]
Fixed in
