### ISSUE TITLE
Clicking No on Update crashes Automato

### ISSUE THREAD

**Issue by Cegaiel** [DashingStrike/Automato-ATITD#119]
While the green Update button is lit up:
* Click Yes to the first Yes/No question (Update from GitHub)?
* After the file check is done, you'll see something like this:

![automato](https://user-images.githubusercontent.com/1331203/37601517-1ef28536-2b82-11e8-9e32-047817d0a719.png)

Clicking No here crashes Automato for me.

I've also just tested this when the Update button is NOT lit up, it still crashes it.

So for this test, just change one of your local files. Click the Update button until it shows you list of files that needs updated. Hit No, it crashes.

**Comment by Jimbly** [comment]
Thanks for the report!  I've fixed this in the source code, will be live when I next do an Automato release.

**Comment by Jimbly** [comment]
Also, actual issues with Automato, not ATITD-specific should be filed here: https://github.com/DashingStrike/Automato/issues although people seem to generally file either one in either place, so perhaps I should just merge them =)

**Comment by Jimbly** [comment]
Fixed in v2.21
