### ISSUE TITLE
Consider setting up a Discord Channel with Github webhook

### ISSUE THREAD

**Issue by Cegaiel** [DashingStrike/Automato-ATITD#120]
I've found that Discord is now a very popular and flexible chat program today.

Even ATITD ( https://discord.gg/hHfbujH ) has one now and it's very busy and players love and use it daily, including myself. There is both a web page based and standalone program. The standalone is much more superior.

With that said, I'm a volunteer dev on another MMO out there that uses GitHub for everything and Discord as primary chat. Normal players don't have access to the GitHub messages in Discord, but devs have a channel they created that uses the webhook offered by both GitHub and Discord to display issues and commits in real time.

Since Automato/ATITD is public access anyways, then it doesn't need to be hidden.

It looks something like this in Discord:
![github_discord](https://user-images.githubusercontent.com/1331203/37605708-adf2eb78-2b8b-11e8-8365-bdbe706671e7.png)

I'd love it Jimbly could create a server for Automato on Discord (It's free, easy to setup and requires no local resources). It's all in the 'cloud'.

Anyone interested in macros or ATITD Automato (heck can go wild and setup a different room for all the games).

I'm very interested in one of the room called 'Updates" or Git_Updates or whatever that has a webhook to GitHub , so that all commits, issues, etc appear in realtime.

Here's some info about it:
https://gist.github.com/eslachance/40ac1c8232a5a019b43ee3f588d637ad
https://support.discordapp.com/hc/en-us/articles/228383668

It's pretty painless. You just go into the Room settings on Discord, and create a Webhook. It then gives you a copy/paste URL that you then copy/paste into the Repo Settings of Github's .  Once that's done, then all the stuff you normally receive in emails, starts appearing in the channel, in realtime.

Almost all atitd players are on discord now and those interested in macros or Automato ATID in general would love to see this appear as sort of a 'news feed'.  Once they join the server in discord, any new messages lights up, even if they aren't in the server or room.

**Comment by Jimbly** [comment]
Good suggestion!  The channel has now been set up [here](https://discord.gg/XVUdwy8) and webhooks seem to be working.  I'll add an in-app link and links to the webpages, wiki, etc.
