### ISSUE TITLE
Launches but at maximum window and cannot click any buttons

### ISSUE THREAD

**Issue by Iratia** [DashingStrike/Automato-ATITD#138]
I used to use veggietales on desktops so i know what size the window is *supposed* to be. On this laptop when I try to use it, it opens like this:
![automatoi](https://user-images.githubusercontent.com/38143621/38442941-e1823eaa-399e-11e8-919c-e401232e5a11.png)
and you cannot click any buttons. The crawl by the way runs (regarding the discord channel). I just have to use the close window button to exit. 
Help meeeee. It's windows 10. 
edit: Oh and no you can't resize the window. I can hover over the tray icon and minimize it which just makes it minimize off the screen.

**Comment by Jimbly** [comment]
What happens when you click the "restore" button the upper left (the one between minimize and close)?

Are you running any window-management programs that might be trying to change the size of windows, or "remember" their previous sizes/positions?

Check your shortcut to Automato - right click on it, go to properties, any chance it's been changed to "Run: Maximized"?  Try changing it back to "Normal window" if so.

**Comment by Iratia** [comment]
nothing happens with restore, and it is set to normal window in shortcut settings. Let me get back to you on the middle option. That takes thinking.

**Comment by Iratia** [comment]
ya I dunno how to answer about a window-management program. I certainly didn't intentionally install one but this *is* a ridiculous HP laptop that came preinstalled with some silly things so.... if anyone knows what I should be looking for and where within windows to find a setting to make it not do that, I'd be so happy.

**Comment by Iratia** [comment]
Ya it doesn't respond to that restore button at all.

**Comment by Iratia** [comment]
and you are right it highlights when i mosue over it. it just doesn't change anything

**Comment by Iratia** [comment]
Turns out nothing a reinstall of windows et. al. won't fix. ;D

**Comment by Jimbly** [comment]
Heheh.  Glad it's working for you now!
