### ISSUE TITLE
ToxinKitchen.lua

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato-ATITD#159]
Submitter: PASCAL G DEBOECK
Email: pdeboeck@indiana.edu
Fails with message "363: attempt to call a nil value (field 'pow')"
I tried to debug and found it goes wrong on line 65 of the lua:  state.volume = ocrNumber(image[0] + 43, image[1]);

**Comment by Cegaiel** [comment]
Fixed with commit: https://github.com/DashingStrike/Automato-common/commit/2221542c3502c03e606f0e569c84979f519969aa
