### ISSUE TITLE
Configurable exit/pause keys

### ISSUE THREAD

**Issue by whaleberg** [DashingStrike/Automato-ATITD#185]
I often have automato + atitd on one half of the screen and a browser on the other.  I notice that I keep accidentally quitting the scripts because `ctrl + shift +tab` is a common browser shortcut.  Would it be possible / sane to make these configurable?  It looks like it might be implemented in every script independently so it might be tricky to do so.

**Comment by Jimbly** [comment]
They actually already are!  A bit hacky, in that it redefines what "ctrl" is (scripts still check "is Ctrl held"), but you can remap them to whatever you want.  Take a look at the wiki [here](https://github.com/DashingStrike/Automato/wiki/Settings).

**Comment by whaleberg** [comment]
Oh, that's great!  Thank you for pointing that out.
