### ISSUE TITLE
Request to add a function to Automato engine

### ISSUE THREAD

**Issue by wzydhek** [DashingStrike/Automato-ATITD#3]
I have found it impossible to use the srKeyEvent to send characters such as '+', '-' and ',' (and I am sure others). In addition, sent characters are capitalized.

I have added a function in older VT code to allow for better sending of character strings. Perhaps it could be integrated with the new Automato code. this function uses the WM_CHAR message to send string data instead of the WM_KEYDOWN and WM_KEYUP messages needed to send key presses.

in luaDriven.cpp

AUTO_LUA;
static void srSendString(const char *s)
{
	for (const unsigned char *c = (const unsigned char *)s; *c; c++)
		strEvent(*c);
}

in ScreenReader.cpp

void strEvent(unsigned char c)
{
	WPARAM wparam;
	if (c == '\n')
		c = '\r';
	wparam = c;
	PostMessage(windowToGrab, WM_CHAR, wparam, 0);
}

in ScreenReader.h

void strEvent(unsigned char c);

**Comment by Jimbly** [comment]
The "new" Automato code is mostly just a re-branding with the couple new features and the code is mostly the same and still available at svn://bigscreensmallgames.com/other/VeggieTales (should have anonymous read access, I can get you write access if you have anything significant you want to commit).  I'd move it to GitHub but it's got tendrils of dependencies on my engine I use for other and commercial projects and nothing in Git is quite as convenient as SVN externals for that kind of thing...

That change looks reasonable though, I'll see if I can test it and push out a new version soon.

**Comment by Jimbly** [comment]
Published Automato v2.05 with this API, I renamed it to srCharEvent since it matches srKeyEvent but sends WM_CHAR messages.  Didn't really test it though, let me know if it works for you =)

**Comment by wzydhek** [comment]
Will do. Also, I modified the “void clickMouse2WindowPos(int vx, int vy, bool rightClick)” method in ScreenReader.cpp.

 

I replaced WPARAM from MK_LBUTTON and MK_RBUTTON to 0. This fixes an issue where if you are doing a srClickMouseNoMove and your screen cursor is elsewhere, occaisionally the POINT you are “clicking” gets dragged to the current mouse location. Often times this results in a game window being moved elsewhere on the game screen. Most noticeable if your mouse cursor is currently on another application. It has been most annoying. This fix solved that issue.

 

From:

 

void clickMouse2WindowPos(int vx, int vy, bool rightClick)

{

                if (rightClick)

                {

                                PostMessage(windowToGrab, WM_RBUTTONDOWN, MK_RBUTTON, MAKELPARAM(vx, vy));

                                PostMessage(windowToGrab, WM_RBUTTONUP, MK_RBUTTON, MAKELPARAM(vx, vy));

                } else {

                                PostMessage(windowToGrab, WM_LBUTTONDOWN, MK_LBUTTON, MAKELPARAM(vx, vy));

                                PostMessage(windowToGrab, WM_LBUTTONUP, MK_LBUTTON, MAKELPARAM(vx, vy));

                }

}

 

To :

 

void clickMouse2WindowPos(int vx, int vy, bool rightClick)

{

                if (rightClick)

                {

                                PostMessage(windowToGrab, WM_RBUTTONDOWN, 0, MAKELPARAM(vx, vy));

                                PostMessage(windowToGrab, WM_RBUTTONUP, 0, MAKELPARAM(vx, vy));

                } else {

                                PostMessage(windowToGrab, WM_LBUTTONDOWN, 0, MAKELPARAM(vx, vy));

                                PostMessage(windowToGrab, WM_LBUTTONUP, 0, MAKELPARAM(vx, vy));

                }

}

**Comment by Jimbly** [comment]
Good catch, yeah, I don't think that parameter should be what it was!  Maybe in button up case but not the button down case... seems to work fine with it zero everywhere (and in mouseDownWindowPos above) though, so I've made the change and published as v2.06.

**Comment by wzydhek** [comment]
Awesome :)

 

-Walt Zydhek
