### ISSUE TITLE
Anonymous issue reporting

### ISSUE THREAD

**Issue by Aoreias** [DashingStrike/Automato-ATITD#43]
To help users be able to submit issues without having to create a user, any thoughts on configuring this repo with [GitReports](https://gitreports.com/)?

**Comment by Jimbly** [comment]
Done for ATITD and Automato:
https://gitreports.com/issue/DashingStrike/Automato-ATITD
https://gitreports.com/issue/DashingStrike/Automato

Will need to add links to GitHub project READMEs (feel free to send PR), website (I'll do this tomorrow), and in-app (perhaps a "feedback" button on the main page and the ATITD script page).

**Comment by Jimbly** [comment]
Links added to all appropriate places, including in-app.
