### ISSUE TITLE
This is a test

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato-ATITD#44]
Submitter: Anonyjimb
Email: wasteland@writeme.com
Only a test.

**Comment by Jimbly** [comment]
Created via gitreports.com

Hmm, I didn't seem to get an email notification when this was created like I do with regular issues...

**Comment by Jimbly** [comment]
Oh, it created it *as me*, probably since that's how GitReports is authenticated, I probably need to set up something special so I get emails from GitReports since the automatic email will not work from GitHub.

**Comment by Aoreias** [comment]
Yeah, I got the notification since it was posted under a different user. I think the recommended approach is to make a new user and register to GitReports under that user.

**Comment by Jimbly** [comment]
GitReports has an option to also email me explicitly when an issue is created, so I set that for now, might switch it to a different user later, looks like the URL would stay the same.
