### ISSUE TITLE
crematory problem

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato-ATITD#51]
Submitter: Teper
Email: tepertoo@gmail.com
when using the crematory macro it does not load the crem properly.
it will load some items but not all and normally does not load the wood, leaving the load tab open covering the fire button which stops the macro.
this could be because my lap top is a little slow at opening the tabs.

if the macro could run a little slower at the start or if it could check that the correct tab was open before proceeding this would probably solve it.

alternatively an alternate macro that just did the buttons and you had to load manually would help

thank you 
Teper

**Comment by ldobson** [comment]
Fixed in https://github.com/DashingStrike/Automato-ATITD/pull/80
