### ISSUE TITLE
upgraded thistle gardens

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato-ATITD#52]
Submitter: Hanid
Email: hanid@vermontel.net
Hi,
Since upgrading the gardens I have only been able to use one at a time, after changing the .png file for thisisathistlegarden. Now, since the last update automato, it can not find any thistle gardens. I have tried thistle, custom mixed and new with the same result: error 330.
Any help or work around suggestions would be greatly appreciated.

**Comment by Jimbly** [comment]
@Aoreias Any ideas? I think I saw some changes to thistle stuff a bit ago...

**Comment by Aoreias** [comment]
I'll talk with Hanid - thistle_custom is working for me on my vanilla version of Automato - not sure exactly where her error is appearing from.

**Comment by Aoreias** [comment]
Various issues unrelated to the macro - user was able to get the macro running using stock version of thistle_config.lua

**Comment by Jimbly** [comment]
Thanks for helping her out!
