### ISSUE TITLE
vinetender.lua

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato-ATITD#63]
Submitter: Silden
Email: silden@atitd.roseflag.com
Harvest displays "Couldn't identify this vine type" on the Amusement strain.

**Comment by Viracoocha** [comment]
Is it just "Amusement" and nothing else?  Found an issue with some types, that you have to omit the "#" in the name to get OCR to read it.  IE:  Pascalito#41 I found I had to enter as Pascalito41 for OCR to find it.  the OCR seems to ignore the # character?  I am new to this scripting.  Just a thought though, and it works without and not with.

**Comment by ldobson** [comment]
Closing this issue in favor of https://github.com/DashingStrike/Automato-ATITD/issues/77.

Additionally, yeah, it looks like OCR doesn't correctly parse the pound symbol and just skips it. That's too much of a pain to fix.
