### ISSUE TITLE
The atitd carp blade macro does not work properly

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato-ATITD#66]
Submitter: Jaclyn Masterson
Email: jaclyn.atitd@gmail.com
When you are trying to make a carp blade your avatar runs off because it clicks places besides the anvil, even if you pin your avatar down the macro only produces an 2510 carp blade. Thank you for your amazing program :)

**Comment by Viracoocha** [comment]
I have messed around and cannot get it to work either.  BUT, there are some alternatives.  the drawback is, you have to set this up each time.  But, I use SIMON for many things.  I will pin open my window, and then from there.  record every click it takes, to load and bang out a decent carp blade and unload it.  in f8 view of course.  Set that to run, no stats bases, for however many blades you want.  I usually knock out 100 or 2 at a time.  I cant do the best quality, but with 200 4 to 5k blades, I dont have to make them that often.

**Comment by Cegaiel** [comment]
The https://github.com/DashingStrike/Automato-ATITD/commit/2c5039bc24558ba77cb467e17bc0cb033db60b80 commit  - See History: https://github.com/DashingStrike/Automato-ATITD/commits/master/scripts/CarpBlades.lua on July 17, 2018 should fix most issues.

The main issue was it was written and hard coded to use 1920x1080. It has now been adjusted to scale different resolutions.

![carpblade](https://user-images.githubusercontent.com/1331203/44952519-abee3f80-ae4e-11e8-92e5-591c31ed29fa.png)

Another note, I'd like to point out, that is not well documented. When you build your anvil, you must rotate it 180 degrees from default.  In other words, when you build your anvil, it will be facing North and South.  But you have to hit the rotate button and rotate it 180 degrees. It will look exactly the same.

The way you can tell if an anvil will support carpBlade.lua is the above picture.  The anvil in Red (sharp edge of blade facing right (that's an anvil that was built using default position) will not work.  The on in green (sharp edge of blade facing left) will work.

Also note is that when you first start the macro, it will put a Resin Wedge on the anvil. This is NOT a bug.  The macro is not trying to create a wedge, it is loading it to gather coordinates.  After loading the resign wedge, you will see the mouse hover until it finds the edge. Once complete, it will scrap the project (this means you get your 7 copper refunded back to you) and then it will start making Carp blades.

You want to stand on the left side, right about where I am in screenshot.  If you find the blade isn't quite hitting the 6-7k mark, try taking a step or two and retry.
