### ISSUE TITLE
Fshing macro-ATITD

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato-ATITD#73]
Submitter: Lilyoptra
Email: pcangelnc@hotmail.com
I installed an update a couple days ago and now fishing macro (fishing.lua) doesn't work, error msg is: Looking for Main chat screen..., even tho chat window is open.  Others that have installed update also report this problem.  Those that have not, aren't getting message.  Please look at this.

**Comment by Jimbly** [comment]
@toad, this sounds like a result of #72.

**Comment by ldobson** [comment]
Agreed. I'm seeing if there might be a better way of refactoring that script to be a little more durable than doing a straight image search

**Comment by ldobson** [comment]
Might have gone a little overboard with the refactoring, but...

https://github.com/DashingStrike/Automato-ATITD/pull/74
