### ISSUE TITLE
thistle_new.lua

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato-ATITD#86]
Submitter: Lilyoptra
Email: pcangelnc@hotmail.com
When I run this macro the text says it can use a pinned water barrel.  However, when I try, it errors out because it thinks it's an additional thistle garden so the expected number of gardens is wrong.  My gardens are not by water so I am unable to use this macro (don't have enough jugs to handle all the passes needed).  Any way this can be fixed?  

Also, we have to reimport the new "This is a Thistle Garden.png" from OneBanana's page after every update for this.  Any way that png could be replaced permanently?

Thank you :)

**Comment by Cegaiel** [comment]
Well, better late than never!

Check out notes on this commit: https://github.com/DashingStrike/Automato-ATITD/commit/91fe94f89d4390d6604adb59646e835cfa1c7430

Addresses all issues and some other quality of life improvements.
