### ISSUE TITLE
Glass.lua

### ISSUE THREAD

**Issue by Jimbly** [DashingStrike/Automato-ATITD#91]
Submitter: Bramanaken
Not reading the temp in bench window but does acknowledge when window is closed or another opened.

**Comment by Fluclo** [comment]
Changes to glass.lua needed:

```
Line 4, window_w = 320;
Line 6, temp_width = 95;
Before line 24, add: local numberImageWidth = 7; local numberImageHeight = 11;
Line 28, local pos = srFindImageInRange("glass" .. i .. ".png", x, y, numberImageWidth, numberImageHeight, tol);
Line 45, x = x + numberImageWidth + 1;
Line 47, local pos = srFindImageInRange("glass" .. i .. ".png", x, y, numberImageWidth, numberImageHeight, tol);
Remove line 96, replace with: 
cooking = srFindImageInRange("GlassCooking.png", window_pos[0]-10, window_pos[1], window_w, window_h, tol);
if cooking then
	nothing_cooking = false;
else
	nothing_cooking = true;
end
```


Needs the following new images:
glass0.png: ![glass0](https://user-images.githubusercontent.com/442029/29414073-8590edac-8356-11e7-9ea9-3119028e7b5c.png)
glass1.png: ![glass1](https://user-images.githubusercontent.com/442029/29414072-858faa50-8356-11e7-814a-b85c5e555d9f.png)
glass2.png: ![glass2](https://user-images.githubusercontent.com/442029/29414075-85943d0e-8356-11e7-9059-3a0bb01a9774.png)
glass3.png: ![glass3](https://user-images.githubusercontent.com/442029/29414071-858e91ba-8356-11e7-99b9-15c127f4973d.png)
glass4.png: ![glass4](https://user-images.githubusercontent.com/442029/29414076-85965544-8356-11e7-9fdb-8d6adfc11163.png)
glass5.png: ![glass5](https://user-images.githubusercontent.com/442029/29414074-8591b340-8356-11e7-80bc-eb0b7cec3475.png)
glass6.png: ![glass6](https://user-images.githubusercontent.com/442029/29414080-85b398ca-8356-11e7-87ad-bd7da6507cab.png)
glass7.png: ![glass7](https://user-images.githubusercontent.com/442029/29414077-85a2b37a-8356-11e7-8296-934ef1a2e8cf.png)
glass8.png: ![glass8](https://user-images.githubusercontent.com/442029/29414079-85a6818a-8356-11e7-9dc6-1249e164f26b.png)
glass9.png: ![glass9](https://user-images.githubusercontent.com/442029/29414078-85a67582-8356-11e7-8997-b5175f315e1d.png)
GlassCooking.png: ![glasscooking](https://user-images.githubusercontent.com/442029/29414103-921bd82a-8356-11e7-9fb7-480eb241f270.png)

Needs amendments to the following images:
GlassTemperature.png: ![glasstemperature](https://user-images.githubusercontent.com/442029/29414115-9e11f498-8356-11e7-96c5-f660e15a4a75.png)
GlassTimeToStop.png: ![glasstimetostop](https://user-images.githubusercontent.com/442029/29414114-9e0af7d8-8356-11e7-8e15-b76d4f9701aa.png)

**Comment by Jimbly** [comment]
RE: the new images, just to double check, are you sure you've got the UI scale at default (most other scripts work)?

You should be able to make the edits yourself directly at https://github.com/DashingStrike/Automato-ATITD/blob/master/scripts/glass.lua (will make a "pull request") - just copy and paste the corrected file in, will be less error prone =).  If you use Git directly, you could also upload the images, but Git can be a pain, so if you're not familiar with it, someone else could help with that part.

**Comment by SildenEgypt** [comment]
I have the UI Scale set to allow all macro's to work. There was a UI change on the Glass Benches in the middle of Tale 7 which caused it to break for everyone.

I have submitted a pull request, as it's my first, it may need extra scrutiny to ensure it's done right.

**Comment by Jimbly** [comment]
Great, thanks for submitting a pull request, it's been merged!  I think all of the recent experts on ATITD macroing have stopped playing, I haven't played since Tale 4, I just maintain the Automato code (and sometimes use it for other games), so I'll accept pretty much any pull requests as-is =).  If anyone steps up and wants to review PRs they're welcome to, but the ATITD scripts have been inactive enough that I'm happy to see any contributions =)
